from __future__ import annotations

import re

PLATFORMS: dict[str, dict] = {
    "github": {
        "url": "https://github.com/{u}",
        "exists": re.compile(r'itemprop="additionalName">\s*{u}\s*</span>|"login"\s*:\s*"{u}"', re.I),
        "name": re.compile(r'<span class="p-name[^"]*"[^>]*>\s*([^<]+?)\s*</span>'),
        "bio": re.compile(r'<div class="p-note user-profile-bio[^"]*"[^>]*>(.*?)</div>', re.S),
        "avatar": re.compile(r'<img[^>]+class="[^"]*avatar[^"]*"[^>]+src="([^"]+)"'),
    },
    "gitlab": {
        "url": "https://gitlab.com/{u}",
        "exists": re.compile(r"<title>[^<]*{u}", re.I),
        "name": re.compile(r'<span class="username"[^>]*>\s*([^<]+?)\s*</span>'),
        "bio": re.compile(r'<p class="profile-tab-bio[^"]*"[^>]*>(.*?)</p>', re.S),
        "avatar": re.compile(r'<img[^>]+class="avatar-tile[^"]*"[^>]+src="([^"]+)"'),
    },
    "reddit": {
        "url": "https://www.reddit.com/user/{u}/about.json",
        "kind": "json",
        "exists": re.compile(r'"name"\s*:\s*"{u}"', re.I),
        "json_name": "name",
        "json_title": "subreddit.title",
        "json_about": "subreddit.public_description",
        "json_avatar": "icon_img",
    },
    "twitch": {
        "url": "https://www.twitch.tv/{u}",
        "exists": re.compile(r"<title[^>]*>\s*{u}\s*(?:on Twitch)?", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "pinterest": {
        "url": "https://www.pinterest.com/{u}/",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "tiktok": {
        "url": "https://www.tiktok.com/@{u}",
        "exists": re.compile(r'"uniqueId"\s*:\s*"{u}"', re.I),
        "name": re.compile(r'"nickname"\s*:\s*"([^"]+)"'),
        "bio": re.compile(r'"signature"\s*:\s*"([^"]*)"'),
        "avatar": re.compile(r'"avatarLarger"\s*:\s*"([^"]+)"'),
    },
    "instagram": {
        "url": "https://www.instagram.com/{u}/",
        "exists": re.compile(r'<meta property="og:title" content="[^"]*{u}', re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "x": {
        "url": "https://x.com/{u}",
        "exists": re.compile(r'<meta property="og:title" content="[^"]*\(@{u}\)', re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "medium": {
        "url": "https://medium.com/@{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "devto": {
        "url": "https://dev.to/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "keybase": {
        "url": "https://keybase.io/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<h1 class="[^"]*profile__name[^"]*"[^>]*>([^<]+)</h1>'),
        "bio": re.compile(r'<div class="[^"]*profile__bio[^"]*"[^>]*>(.*?)</div>', re.S),
        "avatar": re.compile(r'<img class="[^"]*profile-avatar[^"]*"[^>]+src="([^"]+)"'),
    },
    "aboutme": {
        "url": "https://about.me/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "linktree": {
        "url": "https://linktr.ee/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "soundcloud": {
        "url": "https://soundcloud.com/{u}",
        "exists": re.compile(r'"username"\s*:\s*"{u}"', re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "vimeo": {
        "url": "https://vimeo.com/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "kick": {
        "url": "https://kick.com/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "chesscom": {
        "url": "https://www.chess.com/member/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "steam": {
        "url": "https://steamcommunity.com/id/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "kaggle": {
        "url": "https://www.kaggle.com/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "hackerone": {
        "url": "https://hackerone.com/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "tryhackme": {
        "url": "https://tryhackme.com/p/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "hackthebox": {
        "url": "https://app.hackthebox.com/users/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "npm": {
        "url": "https://www.npmjs.com/~{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "pypi": {
        "url": "https://pypi.org/user/{u}/",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r"<h1[^>]*class=\"header[^>]*>\s*([^<]+)\s*</h1>"),
        "bio": re.compile(r'<div class="description[^"]*"[^>]*>(.*?)</div>', re.S),
        "avatar": re.compile(r'<img class="avatar"[^>]+src="([^"]+)"'),
    },
    "docker": {
        "url": "https://hub.docker.com/u/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "behance": {
        "url": "https://www.behance.net/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "dribbble": {
        "url": "https://dribbble.com/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "roblox": {
        "url": "https://www.roblox.com/users/profile?username={u}",
        "kind": "redirect",
        "exists": re.compile(r"users/(\d+)/profile"),
    },
    "leetcode": {
        "url": "https://leetcode.com/{u}/",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "codeforces": {
        "url": "https://codeforces.com/profile/{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<div class="handle"[^>]*>\s*([^<]+)\s*</div>'),
        "bio": re.compile(r'<div class="user-rank"[^>]*>\s*([^<]+)\s*</div>'),
        "avatar": re.compile(r'<img class="avatar"[^>]+src="([^"]+)"'),
    },
    "mastodon_social": {
        "url": "https://mastodon.social/@{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "threads": {
        "url": "https://www.threads.net/@{u}",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "tumblr": {
        "url": "https://{u}.tumblr.com/",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
    "blogger": {
        "url": "https://{u}.blogspot.com/",
        "exists": re.compile(r"<title[^>]*>.*?{u}", re.I),
        "name": re.compile(r'<meta property="og:title" content="([^"]+)"'),
        "bio": re.compile(r'<meta property="og:description" content="([^"]+)"'),
        "avatar": re.compile(r'<meta property="og:image" content="([^"]+)"'),
    },
}
